import "./globals.css";
import { Inter, Lato } from "next/font/google";
import { Major_Mono_Display } from "next/font/google";
import { Bangers } from "next/font/google";

const lato = Lato({ subsets: ["latin"], weight: "400" });
// const inter = Inter({ subsets: ["latin"] });
// const majorMono = Major_Mono_Display({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
